[pyprland]
plugins = ["fetch_client_menu", "scratchpads"]

[fetch_client_menu]
menu = "wofi"

[scratchpads.taskManager]
command = "missioncenter"
animation = "fromTop"
size = "80% 75%"
max_size = "1920px 100%"
margin = 40
lazy = true

[scratchpads.gpu]
command = "lact"
animation = "fromTop"
size = "80% 75%"
max_size = "1920px 100%"
margin = 40
lazy = true

 
# TODO: - add layout_center plugin 