[pyprland]
plugins = ["expose", "scratchpads", "layout_center"]

[scratchpads.taskManager]
command = "missioncenter"
animation = "fromTop"
size = "80% 75%"
max_size = "1920px 100%"
margin = 40
lazy = true

[layout_center]
margin = 40
