[pyprland]
plugins = ["scratchpads", "layout_center"]

[scratchpads.taskManager]
command = "missioncenter"
animation = "fromTop"
size = "65% 60%"
max_size = "2560px 100%"
margin = 70
lazy = true

[layout_center]
margin = 50
offset = [0, 25]
