[pyprland]
plugins = ["expose", "scratchpads", "layout_center"]

[expose]
menu = "wofi"

[scratchpads.taskManager]
command = "missioncenter"
animation = "fromBottom"
size = "80% 75%"
max_size = "1920px 100%"
margin = 40
lazy = true

[layout_center]
margin = 40